quarkus.http.port=8080

app.api.limit=${APP_API_LIMIT:200}
app.api.timeout=${APP_API_TIMEOUT:4000}

quarkus.smallrye-openapi.enable=true
quarkus.smallrye-openapi.info.title=Quarkus Rate Limiting API
quarkus.smallrye-openapi.info.version=1.0.0
quarkus.swagger-ui.always-include=true

# Enable Prometheus metrics endpoint
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder-enabled-default=true

# Metrics path (default is /q/metrics in recent versions)
quarkus.micrometer.export.prometheus.path=/q/metrics

